rasterizer:
  command: phantomjs   # phantomjs executable
  port: 3001           # internal service port. No need to allow inbound or outbound access to this port
  host: '127.0.0.1'    # host to listen on
  path: '/Users/well/WWW/mobiliza/thumb-as-a-service/temp/'        # where the screenshot files are stored
  viewport: '1024x600' # browser window size. Height frows according to the content
server:
  port: 3000           # main service port
  host: '127.0.0.1'    # host to listen on
  useCors: true       # enable CORS support
